source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'SDDispatchTimer_Example' do
  pod 'SDDispatchTimer', :path => '../'

  target 'SDDispatchTimer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
