use_frameworks!

platform :ios, '10.0'

target 'SDDispatchTimer_Example' do
  pod 'SDDispatchTimer', :path => '../'

  target 'SDDispatchTimer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
